-- Vigencia con hora editable (obs 10) + datos de contacto del contratante a
-- nivel propuesta, editables y usados por el PDF (obs 4 y 12).
ALTER TABLE "Proposal" ADD COLUMN     "contratanteCelular" TEXT,
ADD COLUMN     "contratanteEmail" TEXT,
ADD COLUMN     "contratantePhone" TEXT,
ADD COLUMN     "endTime" TEXT,
ADD COLUMN     "startTime" TEXT;

-- Documento auto-generado por el sistema (obs 14: PDF de propuesta guardado al
-- enviarla a la compañía).
ALTER TABLE "Document" ADD COLUMN     "autoGenerated" BOOLEAN NOT NULL DEFAULT false;

-- Ciudad del contratante, separada de la comuna (obs 13: el PDF muestra
-- dirección, comuna, ciudad y región).
ALTER TABLE "Client" ADD COLUMN     "city" TEXT;
